#!/usr/bin/env python
# -*- encoding: utf-8 -*-
import optparse
import pyntervalslib
from pyntervalslib.pyntervals import Pyntervals
from pyntervalslib.version import APP_VERSION


def main():
    parser = optparse.OptionParser(version="%prog " + APP_VERSION)
    parser.add_option("-t", "--token", dest="token", help=u"Token you must get from http://xx.timetask.com/account/api in order to use this tool.", metavar="STRING")
    parser.add_option("--id", dest='id', help=u"Use given ID for some actions to have specific one intead of several of them", metavar='INTEGER')
    parser.add_option("--action", action='store', dest='action', help=u"Action to do with API")
    parser.add_option("--xml", action='store_true', dest='xml', help=u"Returns response as XML. If not given, JSON is used.")
    (options, args) = parser.parse_args()

    if options.token:
        p = Pyntervals(options.token)

        if options.xml:
            p.use_xml()
        else:
            p.use_json()

        if Pyntervals.action_exists(options.action):
            print p.get_action(options.action, options.id)

if __name__ == "__main__":
    main()
